import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>EventBrite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />

          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about">About</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {
          data.map((event) => {
            return(
              <Link href={`/events/${event.id}`} key={event.id}>
                  <Image src={event.image} alt={event.title} height={300} width={300}/>
                  <h2>{event.title}</h2>
                  <p>{event.description}</p>
              </Link>
            );
          })
        }
      </main>
    </>
  );
}

// NextJs is gonna run this ServerSide function first, then it'll run the Home component.
// The ServerSide only runs on the server, never runs on the browser.
export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');

  return {
    props: {
      data: events_categories,
    }
  }
}