import Head from "next/head";

import HomePage from '../src/components/home/home-page.component.jsx';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>EventBrite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data}/>
    </>
  );
}

// NextJs is gonna run this ServerSide function first, then it'll run the Home component.
// The ServerSide only runs on the server, never runs on the browser.
export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');

  return {
    props: {
      data: events_categories,
    }
  }
}